services:
  auth:
    build: 
      context: .
      dockerfile: ./cmd/auth/Dockerfile
    ports:
      - "8080:8080"
  autolog-api:
    build: 
      context: .
      dockerfile: ./cmd/autolog-api/Dockerfile
    ports:
      - "8081:8080"
  