services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  auth:
    build: 
      context: .
      dockerfile: ./cmd/auth/Dockerfile
    ports:
      - "8080:8080"
    env_file: "./cmd/auth/.env"
  autolog-api:
    build: 
      context: .
      dockerfile: ./cmd/autolog-api/Dockerfile
    ports:
      - "8081:8080"
    env_file: "./cmd/autolog-api/.env"
    depends_on:
      auth: 
        condition: service_started #https://github.com/compose-spec/compose-spec/blob/main/spec.md
  images-api:
    build: 
      context: .
      dockerfile: ./cmd/images/Dockerfile
    ports:
      - "8082:8080"
    env_file: "./cmd/images/.env"
    depends_on:
      auth: 
        condition: service_started #https://github.com/compose-spec/compose-spec/blob/main/spec.md
  